image: rozum/embed-gcc:latest

stages:
  - document
  
before_script:
  - eval $(ssh-agent)
  - echo "$COMPANY_SRV_SSH_PRIVATE_KEY" | ssh-add -

document:
 stage: document
 script: 
    - git checkout master
    - git reset --hard HEAD
    - git pull
    - git config --global credential.helper store
    - echo "$GITHUB_CREDENTIALS" > ~/.git-credentials
    - git push -f "$GITHUB_URL" master
    - cd c
    - doxygen
    - cd latex
    - make
    - cd ..
#    - ssh -o StrictHostKeyChecking=no "$COMPANY_SRV" "echo HELLO"
#    - ssh "$COMPANY_SRV" "rm -fr $COMPANY_SRV_DOC_DIR"
    - scp -o StrictHostKeyChecking=no -r html/* "$COMPANY_SRV":"$COMPANY_SRV_DOC_DIR"
    - scp -o StrictHostKeyChecking=no -r latex/refman.pdf "$COMPANY_SRV":"$COMPANY_SRV_DOC_DIR/RR-UserAPI.pdf"
 artifacts:
    paths:
     - c/html
     - latex/refman.pdf
    expire_in: 1 month
 only:
    - master

variables:
  GIT_SUBMODULE_STRATEGY: recursive
