image: rozum/embed-gcc:latest

stages:
  - document
  
before_script:
  - eval $(ssh-agent)
  - echo "$COMPANY_SRV_SSH_PRIVATE_KEY" | ssh-add -

document:
 stage: document
 script: 
    - git checkout master
    - git reset --hard HEAD
    - git pull
    - git config --global credential.helper store
    - echo "$GITHUB_CREDENTIALS" > ~/.git-credentials
    - git push -f "$GITHUB_URL" master
    - git tag
    - cd c
    - ( cat Doxyfile ; echo "PROJECT_NUMBER=$(git tag --contains HEAD)" ) | doxygen -  
    - cd latex
    - make
    - cd ..
    - mkdir archive
    - cp doc-src/arch-list.php html
    - cp latex/refman.pdf html/RR-UserAPI.pdf
    - tar -czvf archive/rr-servoapi-doc-$(git tag --contains HEAD | tr -d '\n').tar.gz html
#    - ssh -o StrictHostKeyChecking=no "$COMPANY_SRV" "echo HELLO"
#    - ssh "$COMPANY_SRV" "rm -fr $COMPANY_SRV_DOC_DIR"
    - scp -o StrictHostKeyChecking=no -r html/* "$COMPANY_SRV":"$COMPANY_SRV_DOC_DIR"
    - scp -o StrictHostKeyChecking=no -r archive "$COMPANY_SRV":"$COMPANY_SRV_DOC_DIR"
 artifacts:
    paths:
     - c/html
     - c/html/RR-UserAPI.pdf
    expire_in: 1 month
 only:
    - master

variables:
  GIT_SUBMODULE_STRATEGY: recursive
