image: rozum/embed-gcc:latest

stages:
  - document
  
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

document:
 stage: document
 script: 
    - cd c
    - doxygen
 artifacts:
    paths:
     - c/html
    expire_in: 1 month
 only:
    - master

variables:
  GIT_SUBMODULE_STRATEGY: recursive
